apiVersion: apps/v1
kind: Deployment
metadata:
  name: docling-service
  labels:
    app: docling-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docling-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: docling-service
    spec:
      containers:
      - name: docling-service
        image: docling-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: docling-service
spec:
  selector:
    app: docling-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: docling-service
spec:
  to:
    kind: Service
    name: docling-service
  port:
    targetPort: 8080
